import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col`}
      >
        <main className="flex-grow">
          {children}
        </main>

        <footer className="bgCustom flex justify-around footer sm:footer-horizontal bg-neutral text-neutral-content p-10">
          
          <nav>
            <h6 className="footer-title">Company</h6>
            <a className="link link-hover">qui suis-je</a>
            <a className="link link-hover">email: lucas.narguet451@gmail.com</a>
          </nav>
          <nav>
            <h6 className="footer-title">Legal</h6>
            <a className="link link-hover">© 2025 Hacktique. Tous droits réservés.</a>
          </nav>
        </footer>
      </body>
    </html>
  );
}