import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SearchBar from "./component/SearchBar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hacktique",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <div className="navbar bg-base-100 shadow-sm">
              <div className="navbar-start">
                <div className="dropdown">
                  <div tabIndex={0} role="button" className="btn btn-ghost btn-circle">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="white">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h7" />
                    </svg>
                  </div>
                  <ul tabIndex={0} className="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow ">
                    <Link href="/debutant" className="text-white">debutant</Link >
                    <Link href="/intermediaire"  className="text-white">intermediaire</Link >
                    <Link href="/avancer" className="text-white">avancer</Link >
                  </ul>
                </div>
              </div>
              <div className="navbar-center">
                <Link href="/" className="text-xl text-white">Hacktique</Link>
              </div>
              <div className="navbar-end">
                <SearchBar/>
              </div>
            </div>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col`}
      >
        <main className="flex-grow">
          {children}
        </main>

        <footer className="bgCustom flex justify-around footer sm:footer-horizontal bg-neutral text-neutral-content p-10">
          
          <nav>
            <h6 className="footer-title">Company</h6>
            <a className="link link-hover">qui suis-je</a>
            <a className="link link-hover">email: lucas.narguet451@gmail.com</a>
          </nav>
          <nav>
            <h6 className="footer-title">Legal</h6>
            <a className="link link-hover">© 2025 Hacktique. Tous droits réservés.</a>
          </nav>
        </footer>
      </body>
    </html>
  );
}